namespace LegendaryTools.MiniCSharp
{
    internal enum TokenType
    {
        LeftParen,
        RightParen,
        LeftBracket,
        RightBracket,
        LeftBrace,
        RightBrace,
        Semicolon,
        Comma,
        Colon,
        Dot,
        Question,
        QuestionDot,
        QuestionQuestion,

        Plus,
        PlusEqual,
        Minus,
        MinusEqual,
        Star,
        StarEqual,
        Slash,
        SlashEqual,
        Percent,
        PercentEqual,

        Bang,
        BangEqual,
        Equal,
        EqualEqual,
        Arrow,
        Greater,
        GreaterEqual,
        Less,
        LessEqual,

        AndAnd,
        OrOr,
        PlusPlus,
        MinusMinus,

        Identifier,
        Number,
        String,
        InterpolatedString,

        True,
        False,
        Null,

        If,
        Else,
        Try,
        Catch,
        Finally,
        Switch,
        Case,
        Default,
        For,
        Foreach,
        In,
        Is,
        As,
        While,
        Break,
        Continue,
        Return,
        Yield,
        Typeof,
        Var,
        New,

        EndOfFile
    }
}
